branches:
    - main
debug: false
ci: true
plugins:
    - '@semantic-release/commit-analyzer'
    - '@semantic-release/release-notes-generator'
    - '@semantic-release/changelog'
    - - '@semantic-release/exec'
      - prepareCmd: 'node -p "JSON.stringify({...require(\"./package.json\"), version: \"${nextRelease.version}\"}, null, 2)" > package.json'
    - - '@semantic-release/npm'
      - npmPublish: true
        tarballDir: dist
    - - '@semantic-release/git'
      - assets:
            - dist/**/*.{js,css,ts}
            - package.json
            - CHANGELOG.md
            - LICENSE
            - README.md
        message: |-
            chore(release): ${nextRelease.version} [skip ci]
            ${nextRelease.notes}
    - - '@semantic-release/github'
      - addReleases: top
