branches:
    - main
tagFormat: 'theme-v${version}'
debug: false
ci: true
plugins:
    - - '@semantic-release/commit-analyzer'
      - parserOpts:
          noteKeywords: ['BREAKING CHANGE', 'BREAKING CHANGES']
        releaseRules:
          - { scope: 'theme', breaking: true, release: 'major' }
          - { scope: 'theme', type: 'feat', release: 'minor' }
          - { scope: 'theme', type: 'fix', release: 'patch' }
          - { scope: 'theme', type: 'perf', release: 'patch' }
          - { scope: 'theme', type: 'chore', release: 'patch' }
          - { scope: 'theme', type: 'refactor', release: 'patch' }
    - '@semantic-release/release-notes-generator'
    - '@semantic-release/changelog'
    - - '@semantic-release/exec'
      - prepareCmd: 'node update-version.js ${nextRelease.version}'
    - - '@semantic-release/npm'
      - npmPublish: true
        tarballDir: dist
    - - '@semantic-release/git'
      - assets:
            - package.json
            - CHANGELOG.md
        message: |-
            chore(release): ${nextRelease.version} [skip ci]
            ${nextRelease.notes}
    - - '@semantic-release/github'
      - addReleases: top
