branches:
    - main
debug: false
ci: true
plugins:
    - '@semantic-release/commit-analyzer'
    - '@semantic-release/release-notes-generator'
    - '@semantic-release/changelog'
    - - '@semantic-release/exec'
      - prepareCmd: 'node update-version.js ${nextRelease.version}'
    - - '@semantic-release/npm'
      - npmPublish: true
        tarballDir: dist
    - - '@semantic-release/git'
      - assets:
            - package.json
            - CHANGELOG.md
        message: |-
            chore(auth): ${nextRelease.version} [skip ci]
            ${nextRelease.notes}
    - - '@semantic-release/github'
      - addReleases: top
